name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Tag the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t akshayvishu/my-devops-task:${{ github.sha }} .
          docker tag akshayvishu/my-devops-task:${{ github.sha }} akshayvishu/my-devops-task:latest

      # Step 4: Push the Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push akshayvishu/my-devops-task:${{ github.sha }}
          docker push akshayvishu/my-devops-task:latest
